[project]
name = "grocery-orders-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AnasElgamed8", email = "anashossamhafez@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "basedpyright>=1.39.10",
    "marimo[lsp]>=0.24.0",
    "matplotlib>=3.11.1",
    "nbconvert>=7.17.1",
    "pandas>=3.0.5",
    "playwright>=1.62.0",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "altair>=6.2.2",
    "nbformat>=5.11.1",
    "python-lsp-ruff>=2.3.3",
    "python-lsp-server>=1.15.0",
    "vegafusion>=2.0.3",
    "vl-convert-python>=1.9.0.post1",
    "websockets>=17.1",
]
